@startuml refresh-token-flow
!pragma teoz true

title Refresh Token Flow

actor "User" as user
participant "Page" as page
participant "Blazor.Auth" as lib
participant "IUserService" as userService
participant "IAuthenticationService" as authService

user -> page: Open Page
activate page
page -> lib: Get User's AuthenticationState
activate lib
lib -> userService: If AccessToken expired,\nRefreshJwtPairAsync
activate userService
userService -> authService: RefreshJwtPairAsync
activate authService
authService -> authService: Your refresh logic
authService --> userService: AuthenticationResult
deactivate authService
userService -> userService: Update Browser Cookies
userService --> lib: AuthenticationResult
deactivate userService
lib --> page: AuthenticationState
deactivate lib
page --> user: Display Page
deactivate page

@enduml