@startuml sign-up-flow
!pragma teoz true

title Sign-Up Flow

actor "User" as user
participant "SignUp Page" as page
participant "IUserService" as userService
participant "IAuthenticationService" as authService

user -> page: Submit Sign-Up Form
activate page
page -> userService: SignUpAsync(signUpPayload)
activate userService
userService -> authService: SignUpAsync(signUpPayload)
activate authService
authService -> authService: Your authentication logic
authService --> userService: AuthenticationResult
deactivate authService
userService -> userService: Update Browser Cookies
userService --> page: AuthenticationResult
deactivate userService
page --> user: Redirect to home page
note right
Upon receiving the AuthenticationResult
from the IUserService, do a page refresh so that
Blazor would update the User's AuthenticationState

Example: NavigationManager.NavigateTo("/", true);
end note

deactivate page

@enduml